# Generated by Django 3.0.3 on 2020-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('experience_type', models.CharField(choices=[('project', 'project'), ('work', 'work')], max_length=200, null=True)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('github_url', models.URLField(null=True)),
            ],
        ),
    ]
