# Generated by Django 3.0.3 on 2020-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200524_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
